# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
      - "network.publish_host=http://elasticsearch:9200"
      - "cluster.name=Dragons"
    networks:
      - network
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - network
  fuse:
    image: yangdb/yang.db:latest
    depends_on:
      - elasticsearch
    ports:
      - 8888:8888
    environment:
      - "elasticsearchHosts=localhost"
      - "elasticsearchClusterName=${ELASTICSEARCH_CLUSTER_NAME}"
    volumes:
      - fuse-data:/usr/share/fuse
    networks:
      - network

volumes:
  fuse-data:
    driver: local
  esdata1:
    driver: local

networks:
  network:
    name: elasticsearch-graphdb-dragons-demo
    attachable: true