{
 "title": "ElasticSearch",
 "description": "ElasticSearch cluster stats",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Сluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+22"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{cluster=\"$cluster\",name=~\"$name\"}>0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "singlestat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total translog operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_operations{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_size_in_bytes{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Tripped for breakers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_tripped{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_breakers_estimated_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{breaker}}"
    },
    {
     "expr": "elasticsearch_breakers_limit_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: limit for {{breaker}}"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_load1{cluster=\"knowledge\",name=~\"ip-172-31-20-222\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-22-107\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-23-134\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-24-199\\\\.eu-north-1\\\\.compute\\\\.internal\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{cluster=\"knowledge\",name=~\"ip-172-31-20-222\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-22-107\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-23-134\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-24-199\\\\.eu-north-1\\\\.compute\\\\.internal\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{cluster=\"knowledge\",name=~\"ip-172-31-20-222\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-22-107\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-23-134\\\\.eu-north-1\\\\.compute\\\\.internal|ip-172-31-24-199\\\\.eu-north-1\\\\.compute\\\\.internal\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "percentunit", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}: {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: sent "
      },
      {
       "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: received"
      }
     ]
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Documents count on node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Total Operations  rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_tota{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "graph",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "graph",
   "gridPos": { "h": 19, "w": 6, "x": 6, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "graph",
   "gridPos": { "h": 19, "w": 6, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "graph",
   "gridPos": { "h": 19, "w": 6, "x": 18, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 177 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Evictions from filter cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 177 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_filter_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Count of index segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current memory size of segments in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of documents with only primary shards",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{instance=~\"$instance\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  { "title": "Indices: Index writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 } },
  {
   "title": "Index writer with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_primary"
    }
   ]
  },
  {
   "title": "Index writer with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Segments with only primary shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Segments with all shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_count_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of segments with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 240 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Doc values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 247 } },
  {
   "title": "Doc values with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Doc values with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 255 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fields", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 262 } },
  {
   "title": "Size of fields with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 263 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fields with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 270 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Fixed bit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 277 } },
  {
   "title": "Size of fixed bit with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 278 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of fixed bit with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 285 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Norms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 292 } },
  {
   "title": "Size of norms with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 293 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of norms with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Indices: Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 307 } },
  {
   "title": "Size of points with only primary shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 308 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_primary{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Size of points with all shards on all nodes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 315 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Indices: Terms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 322 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of terms with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 250 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_terms_memory_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Number of terms with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_terms_memory_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Version map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 323 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of version map with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_version_map_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of version map with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 199 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}